apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: devops-tools-storage-class
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  csi.storage.k8s.io/fstype: ext4
  tagSpecification_1: "env=dev"
