apiVersion: v1
kind: Pod
metadata:
  name: dubug
  namespace: devops-tools
spec:
  containers:
    - name: debug
      image: maxpain62/docker-awscli2.0:1.0.0
      securityContext:
        privileged: true
      command:
        - sleep
        - 3600s
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock
