apiVersion: v1
kind: Pod
metadata:
  name: get-ecr-password
  namespace: devops-tools
spec:
  serviceAccountName: code-artifact-sa
  containers:
    - name: get-ecr-password
      image: amazon/aws-cli
      command:
        - sleep
        - 3600s
